# See NOTE comments for places to modify.
services:
  frontend:
    image: unmute-frontend:latest
    build:
      context: frontend/
      dockerfile: hot-reloading.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src

  backend:
    image: unmute-backend:latest
    build:
      context: ./
      target: hot-reloading
    volumes:
      - ./unmute:/app/unmute
    ports:
      - "8000:80"
    environment:
      - KYUTAI_STT_URL=ws://given-talking-jessica-prefix.trycloudflare.com
      - KYUTAI_TTS_URL=ws://cycling-weekend-previews-sleep.trycloudflare.com
      - KYUTAI_LLM_URL=http://178.164.79.201:40740
      - KYUTAI_LLM_MODEL=Qwen/Qwen2.5-3B-Instruct-AWQ
      - KYUTAI_LLM_API_KEY=7f3e13e003cca375129cf77fa990c5fbd8116aa8940f5136cf51fd3c7566eb2f
      - NEWSAPI_API_KEY=af0f020086be4d1ca1b7236145ecb91e

networks:
  default: